coverage:
  status:
    project:
      default:
        target: "100"
        informational: true
    patch:
      default:
        target: "100"
        informational: true
comment:
  require_changes: true
