* General functions                                                :noexport:
#+begin_src ipython :exports none :session   :results drawer output
  from stats import formatting
  formatting.add_org_formatter_ipython()
#+end_src

#+RESULTS:
:results:
:end:

* Word Analysis

This modules has a set of functions to analyze Spanish words and determine
their difficulty level based on the following dimensions:
1) Word length
2) Number of silent letters
3) Number of different letters with the same sound: e.g., /s/ and /z/ 
4) Number of anagrams: words that can be made with its letters

* Getting Started
** Prerequisites
You will need to install the pandas package to be able to use this
module. To install it use =pip install pandas=.
** Installing
=pip install wdiff=

** Usage
#+begin_src ipython :exports code :session :results drawer output
  import wdiff
  words = ['perro', 'gato', 'serpiente']
  wanalyzer = wdiff.WordAnalyzer()
  wanalyzer.set_words(words)
  wanalyzer.determine_length_difficulty(difficultyWeight=1)
  wanalyzer.determine_silent_letter_difficulty(difficultyWeight=1)
  wanalyzer.determine_same_sound_letter_difficulty(difficultyWeight=1)
  wanalyzer.determine_anagrams_difficulty(difficultyWeight=1)
  wanalyzer.determine_total_difficulty_index()
  wanalyzer.save_results()
#+end_src

#+RESULTS:
:results:
:end:

Results will be saved in the current directory as a CSV file.
* Contributing to this project
  If you encounter any bugs, please open an issue on github. To contribute to
this project, clone the repository and submit a pull request. If you wish to
become an active maintainer of the project, you can contact me
at mbermonti1132@gmail.com

  All contributions are welcome!
* Author
  Mario E. Bermonti-Perez. Feel free to contact me at mbermonti1132@gmail.com.
* License
This project is licensed under the GPL License. See the LICENSE.txt file for
details.
