TODO consider workflow for extending

@startuml responsibilities
!theme spacelab

entity Wdiff{
    public interface
    provides general level functions
    Keep tracks of results state
}

entity Length{
    Analyze letter length of words
}
entity SilentLetters{
    Analyze silent letters in words
    Analyze specific charactertistics 
    Analyze total difficulty 
}

entity SharedPhonemes{
    Analyze shared phonemes in words
    Analyze specific charactertistics 
    Analyze total difficulty 
}

entity cli{
    read words texts from file
    run all analyses
    run individual analyses - future
    save results
}

entity utils{
    normalize words
    format as df
}

Wdiff *-- Length
Wdiff *-- SilentLetters
Wdiff *-- SharedPhonemes
Wdiff *-- utils
cli *-- Wdiff

@enduml

@startuml attributes
!theme spacelab
entity Wdiff {
    - pd.DataFrame _results
    ' +run_all_analyses()
    +None analyze_letter_length()
    +None analyze_silent_letters()
    +None analyze_shared_phonemes()
    +None analyze_total_difficulty()
    +None save_results(filename: Path)
    +pd.DataFrame results() 

    -Iterable[str] normalize_words(Iterable[str])
}

entity Length{
    #int analyze_letter_length(str text)
}
entity SilentLetters{
    #int analyze_u(str text)
    #int analyze_h(str text)
    #pd.Series analyze_total(pd.DataFrame)
}

entity SharedPhonemes{
    #int analyze_s(str text) 
    #int analyze_b(str text)
    #int analyze_y(str text)
    #int analyze_j(str text)
    #int analyze_k(str text)
    #pd.Series analyze_total(pd.DataFrame)
}

' entity cli{
'     +Iterable[str] get_words_from_file(Path filename)
'     +run_all_analyses(Analyzer analyzer)
'     +save_results(Path filename)
' }

Wdiff *-- Length
Wdiff *-- SilentLetters
Wdiff *-- SharedPhonemes

@enduml
