
name: security
on: [push, pull_request]
jobs:
  security:
    name: security
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set up Python 3.8
        uses: actions/setup-python@v2.3.2
        with:
          python-version: 3.8

      - name: Install nox
        run: |
          pip install nox==2021.6.12

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1.3.0
        with:
          version: 1.1.12
          virtualenvs-create: true
          virtualenvs-in-project: false

      - name: Run safety check
        if: matrix.python-version == 3.9 && matrix.os == 'Ubuntu'
        run: nox --force-color -s safety
